Fix YAML syntax

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -9,7 +9,8 @@ runs:
   using: composite
   steps:
     - name: check-os
-      run: [[ "${{ runner.os }}" = Windows ]] && { echo "Error: this action currently does not support Windows runners"; exit 1; }
+      run: |
+        [[ "${{ runner.os }}" = Windows ]] && { echo "Error: this action currently does not support Windows runners"; exit 1; }
       shell: bash
     - name: determine-version
       run: |
