Replace all env vars with outputs

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -3,16 +3,17 @@ description: Installs mikefarah/yq on the job's runner
 author: Daniel Weibel
 inputs:
   version:
-    description: The version of yq to install (by default, the latest version will be installed)
+    description: The version of yq to install (by default, the latest version is installed)
     required: false
   binary:
-    description: The name of the yq binary to install (by default, 'yq_linux_amd64' and 'yq_darwin_amd64' are installed for Linux and macOS runners, respectively)
+    description: The name of the yq binary to install (by default, 'yq_linux_amd64' is used for Linux runners and 'yq_darwin_amd64' for macOS runners)
     required: false
 runs:
   using: composite
   steps:
  
-    - name: commons
+    - name: util
+      id: util
       run: |
         file=$(mktemp)
         cat <<'EOF' >"$file"
@@ -21,20 +22,21 @@ runs:
           exit 1
         }
         EOF
-        echo "COMMONS=$file" >>"$GITHUB_ENV"
+        echo "::set-output name=util::$file"
       shell: bash
  
     - name: check-os
       run: |
-        . "$COMMONS"
+        . "${{ steps.util.outputs.util }}"
         if [[ "${{ runner.os }}" = Windows ]]; then
           fail "This action currently does not support Windows runners"
         fi
       shell: bash
 
     - name: determine-version
+      id: version
       run: |
-        . "$COMMONS"
+        . "${{ steps.util.outputs.util }}"
         VERSION="${{ inputs.version }}"
         if [[ -z "$VERSION" ]]; then
           # Determine latest version
@@ -47,13 +49,14 @@ runs:
             fail "$VERSION is not a valid yq version (see https://github.com/mikefarah/yq/releases for the list of valid versions)"
           fi
         fi
-        echo "VERSION=$VERSION" >>"$GITHUB_ENV"
         echo "Using yq version $VERSION"
+        echo "::set-output name=version::$VERSION"
       shell: bash
 
     - name: determine-binary
+      id: binary
       run: |
-        . "$COMMONS"
+        . "${{ steps.util.outputs.util }}"
         BINARY="${{ inputs.binary }}"
         if [[ -z "$BINARY" ]]; then
           # Use default binaries
@@ -63,25 +66,25 @@ runs:
           esac
         else
           # Verify user-supplied binary
-          stdout=$(wget -q --content-on-error -O - "$GITHUB_API_URL"/repos/mikefarah/yq/releases/tags/"$VERSION") || fail "GitHub API request failed: $stdout"
+          stdout=$(wget -q --content-on-error -O - "$GITHUB_API_URL"/repos/mikefarah/yq/releases/tags/${{ steps.version.outputs.version }}) || fail "GitHub API request failed: $stdout"
           if ! echo "$stdout" | jq -r '.assets[].name' | grep -q "^$BINARY$"; then
-            fail "$BINARY is not a valid binary of yq $VERSION (see https://github.com/mikefarah/yq/releases/$VERSION for the list of valid binaries)"
+            fail "$BINARY is not a valid binary of yq ${{ steps.version.outputs.version }} (see https://github.com/mikefarah/yq/releases/${{ steps.version.outputs.version }} for the list of valid binaries)"
           fi
         fi
-        echo "BINARY=$BINARY" >>"$GITHUB_ENV"
         echo "Using yq binary $BINARY"
+        echo "::set-output name=binary::$BINARY"
       shell: bash
 
     - name: install
       run: |
-        url=https://github.com/mikefarah/yq/releases/download/"$VERSION"/"$BINARY"
+        url=https://github.com/mikefarah/yq/releases/download/${{ steps.version.outputs.version }}/${{ steps.binary.outputs.binary }}
         echo "Installing yq from $url"
         sudo wget -q -O /usr/local/bin/yq "$url" && sudo chmod +x /usr/local/bin/yq
       shell: bash
 
     - name: verify
       run: |
-        . "$COMMONS"
+        . "${{ steps.util.outputs.util }}"
         echo "Verifying installation"
         stderr=$(yq 2>&1 >/dev/null) || fail "Installation verification failed: $stderr"
         echo "Installation of yq successful"
