Improve output

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -18,6 +18,7 @@ runs:
 
     - name: determine-version
       run: |
+        echo -n "Determine yq version: "
         if [[ -z "${{ inputs.version }}" ]]; then
           # Determine latest version
           out=$(wget -q --content-on-error -O - "$GITHUB_API_URL"/repos/mikefarah/yq/releases/latest) || { echo "$out"; exit 1; }
@@ -34,10 +35,12 @@ runs:
           fi
         fi
         echo "VERSION=$VERSION" >>"$GITHUB_ENV"
+        echo "$VERSION"
       shell: bash
 
     - name: determine-binary
       run: |
+        echo -n "Determine yq binary: "
         if [[ -z "${{ inputs.binary }}" ]]; then
           # Use default binaries
           case "${{ runner.os }}" in
@@ -54,20 +57,21 @@ runs:
           fi
         fi
         echo "BINARY=$BINARY" >>"$GITHUB_ENV"
+        echo "$BINARY"
       shell: bash
 
     - name: install
       run: |
-        sudo wget -q -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/"$VERSION"/"$BINARY" &&
-        sudo chmod +x /usr/local/bin/yq
+        url=/usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/"$VERSION"/"$BINARY"
+        echo "Install $url"
+        sudo wget -q -O "$url" && sudo chmod +x /usr/local/bin/yq
       shell: bash
 
     - name: verify
       run: |
-        if out=$(yq 2>&1); then
-          echo "Installation successful: $(yq --version)"
-        else
-          echo "Installation failed: $out"
+        echo "Verify installation"
+        if ! stderr=$(yq >/dev/null); then
+          echo "::error::$stderr"
           exit 1
         fi
       shell: bash
